const regions = {
  "South Africa (Afrikaans)": "af_ZA",
  Arabic: "ar",
  Azerbaijan: "az",
  "Czech Republic": "cz",
  Germany: "de",
  Austria: "de_AT",
  "Switzerland (German)": "de_CH",
  Greece: "el",
  English: "en",
  Australia: "en_AU",
  "Australia (Ocker)": "en_AU_ocker",
  Bork: "en_BORK",
  "Canada (English)": "en_CA",
  "United Kingdom": "en_GB",
  Ghana: "en_GH",
  Ireland: "en_IE",
  India: "en_IND",
  Nigeria: "en_NG",
  "United States": "en_US",
  "South Africa (English)": "en_ZA",
  Spain: "es",
  Mexico: "es_MX",
  "Iran (Farsi)": "fa",
  Finland: "fi",
  France: "fr",
  "Belgium (French)": "fr_BE",
  "Canada (French)": "fr_CA",
  "Switzerland (French)": "fr_CH",
  Georgia: "ge",
  "Israel (Hebrew)": "he",
  Croatia: "hr",
  Hungary: "hu",
  Armenia: "hy",
  Indonesia: "id_ID",
  Italy: "it",
  Japan: "ja",
  Korea: "ko",
  Latvia: "lv",
  Macedonia: "mk",
  Norway: "nb_NO",
  Nepal: "ne",
  Netherlands: "nl",
  "Belgium (Dutch)": "nl_BE",
  Poland: "pl",
  Brazil: "pt_BR",
  Portugal: "pt_PT",
  Romania: "ro",
  Russia: "ru",
  Slovakia: "sk",
  Sweden: "sv",
  Turkey: "tr",
  Ukraine: "uk",
  "Pakistan (Urdu)": "ur",
  Vietnam: "vi",
  China: "zh_CN",
  Taiwan: "zh_TW",
  "South Africa (Zulu)": "zu_ZA",
};

module.exports = { regions };
